spring:
  datasource:
    url: jdbc:h2:mem:engbuddy
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop

openai:
  api:
    key: your-openai-api-key-here
    url: https://api.openai.com/v1
